# Generated by Django 2.2.3 on 2019-07-22 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190722_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='readiness',
            field=models.IntegerField(null=True),
        ),
    ]
